# Site Settings
baseurl: ""
url : "https://arturoalcibia.dev"

# Blog Settings
theme_settings :
  title : Arturo Alcibia
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    username : Arturo Alcibia
    description : I’m a CG pipeline developer with experience in film production. Always wanting to learn more and passionate on problem solving.
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate

# Archives
collections:
  projects:
    output: true
    permalink: /:collection/:path/

bootstrap:
  assets: true

include:
  - _pages
defaults:
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: page
      author_profile: false
      share: true
