# Site Settings
url : "https://arturoalcibia.dev"

# Blog Settings
theme_settings :
  title : Arturo Alcibia
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    username : Arturo Alcibia
    description : I’m a CG pipeline developer with experience in film production. Always wanting to learn more and passionate on problem solving.
    experience :
      - role : Pipeline T.D.
        studio : On Animation Studio
        start : April 2020
        end : April 2021
      - role : Rigging Pipeline T.D.
        studio : L'Atelier Animation
        start : April 2019
        end : April 2020
      - role : Rigging Pipeline T.D.
        studio: Huevocartoon
        start : September 2018
        end : March 2019
      - role : Pipeline T.D.
        studio: MKF Animation
        start : October 2017
        end : September 2018
      - role : Pipeline T.D.
        studio: Cluster Studio
        start : April 2017
        end : October 2017
    skills : 
      - skill : Python
        value : 85
      - skill : C++
        value : 60
      - skill : C#
        value : 40
      - skill : Lua
        value : 40
      - skill : html - css
        value : 40

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate

# Archives
collections:
  projects:
    output: true
    permalink: /:collection/:path/

bootstrap:
  assets: true

include:
  - _pages
defaults:
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: page
      author_profile: false
      share: true
